-- MySQL Script generated by MySQL Workbench
-- Sun Sep 30 13:40:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id7313589_sgctcces
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `id7313589_sgctcces` ;

-- -----------------------------------------------------
-- Schema id7313589_sgctcces
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `id7313589_sgctcces` DEFAULT CHARACTER SET utf8 ;
USE `id7313589_sgctcces` ;

-- -----------------------------------------------------
-- Table `id7313589_sgctcces`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7313589_sgctcces`.`Alunos` (
  `CPF` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(14) NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `municipio` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `email_aluno_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7313589_sgctcces`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7313589_sgctcces`.`Cursos` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ano_oferta` INT NOT NULL,
  `semestre_oferta` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `id_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7313589_sgctcces`.`Matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7313589_sgctcces`.`Matriculas` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `Alunos_CPF` VARCHAR(11) NOT NULL,
  `Cursos_codigo` INT NOT NULL,
  PRIMARY KEY (`Alunos_CPF`, `Cursos_codigo`),
  UNIQUE INDEX `codigo_matricula_UNIQUE` (`codigo` ASC),
  INDEX `fk_Matriculas_Alunos1_idx` (`Alunos_CPF` ASC),
  INDEX `fk_Matriculas_Cursos1_idx` (`Cursos_codigo` ASC),
  CONSTRAINT `fk_Matriculas_Alunos1`
    FOREIGN KEY (`Alunos_CPF`)
    REFERENCES `id7313589_sgctcces`.`Alunos` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matriculas_Cursos1`
    FOREIGN KEY (`Cursos_codigo`)
    REFERENCES `id7313589_sgctcces`.`Cursos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7313589_sgctcces`.`Avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7313589_sgctcces`.`Avaliacoes` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `Cursos_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Avaliacoes_Cursos1_idx` (`Cursos_codigo` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  CONSTRAINT `fk_Avaliacoes_Cursos1`
    FOREIGN KEY (`Cursos_codigo`)
    REFERENCES `id7313589_sgctcces`.`Cursos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7313589_sgctcces`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7313589_sgctcces`.`Notas` (
  `Avaliacoes_codigo` INT NOT NULL,
  `Alunos_CPF` VARCHAR(11) NOT NULL,
  `nota` DECIMAL NOT NULL,
  PRIMARY KEY (`Avaliacoes_codigo`, `Alunos_CPF`),
  INDEX `fk_Notas_Alunos1_idx` (`Alunos_CPF` ASC),
  CONSTRAINT `fk_Notas_Avaliacoes1`
    FOREIGN KEY (`Avaliacoes_codigo`)
    REFERENCES `id7313589_sgctcces`.`Avaliacoes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Alunos1`
    FOREIGN KEY (`Alunos_CPF`)
    REFERENCES `id7313589_sgctcces`.`Alunos` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- insere dados do aluno
INSERT INTO `Alunos` (`CPF`, `nome`, `telefone`, `email`, `senha`, `endereco`, `municipio`, `estado`) VALUES ('38958676400', 'Arka Brebe Covan', '(82)2685-6905', 'aluno@sgc.tcc.es', '202cb962ac59075b964b07152d234b70', 'Rua do Comércio 123, Centro', 'Belém', 'AL');